Code coverage
noelbundick/config-analyzer pull request #17
Opened 2021-02-04 22:44 UTC by Joshua-Phelps

closes #16 

- installed and configured nyc package to work with mocha and typescript
- I chose to use istanbul/nyc because it works well with mocha and has options to work with typescript

2021-02-05 17:48 UTC, noelbundick requested changes
looks good! Maybe a few tweaks - particularly for bailing on tests

2021-02-05 17:48 UTC, noelbundick commented on .mocharc.yml
> +bail: true
Let's remove this line so we get all failures in CI

2021-02-05 17:48 UTC, noelbundick commented on package.json
> +    "instrument": true
Let's find out what this does or remove it

2021-02-05 17:48 UTC, noelbundick commented on package.json
> +      "html"
nit: do we need html output?

2021-02-05 17:48 UTC, noelbundick commented on .mocharc.yml
> +bail: true
```suggestion
```

2021-02-05 17:49 UTC, noelbundick commented on package.json
> +    "instrument": true
```suggestion
    "sourceMap": true
```

2021-02-05 18:12 UTC, Joshua-Phelps reviewed
lgtm

2021-02-08 17:06 UTC, noelbundick approved these changes
lgtm

2021-02-08 17:06 UTC, merged